development:
  adapter: postgresql
  encoding: unicode
  database: capteste_development
  pool: 5
  username: thoughtworks
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: capteste_test
  pool: 5
  username: capteste
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: capteste_production
  pool: 5
  username: capteste
  password:
